services:

  api:
    container_name: api_trexx
    build:
      dockerfile: Dockerfile-api
      context: .
      target: development
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:5437/${DATABASE_NAME}?schema=public
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
      - ${DEBUGGER_PORT}:${DEBUGGER_PORT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres_trexx
    build:
      dockerfile: Dockerfile-postgres
      context: .
      target: development
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5437:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis_trexx
    build:
      dockerfile: Dockerfile-redis
      context: .
      target: development
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6381:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
    name: postgres-data
  redis-data:
    name: redis-data
